# Generated by Django 2.2.4 on 2019-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20191107_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default=' https://zabas.com/wp-content/uploads/2014/06/placeholder-food-hover.png ', max_length=500),
        ),
    ]
