# Generated by Django 2.2.4 on 2019-11-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20191107_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default=' https://img.etimg.com/thumb/msid-65511444,width-643,imgsize-487093,resizemode-4/food-eat-bbq-meat-gettyimages-673139382.jpg ', max_length=500),
        ),
    ]
